name: noor_al_hidayah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  geolocator: ^14.0.3
  http: ^1.6.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  screenshot: ^3.0.0
  share_plus: ^13.3.0
  cross_file: ^0.3.5+5
  scrollable_positioned_list: ^0.3.8
  just_audio: ^0.10.6
  just_audio_background: ^0.0.1-beta.17
  path_provider: ^2.1.6
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_messaging: ^16.0.0
  onesignal_flutter: ^5.2.0
  google_sign_in: ^6.2.1
  wakelock_plus: ^1.2.8
  flutter_compass: ^0.8.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  audioplayers: ^6.1.0
  record: ^5.1.2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image: ^4.2.0
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# ✅ حل تعارض record
dependency_overrides:
  record_linux: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/icons/
    - assets/images/backgrounds/
    - assets/images/adhan_backgrounds/
    - assets/icons/owner.png
    - assets/icons/premium.png
