import 'package:flutter/material.dart';

import 'strings_prayer.dart';

class AppState extends ChangeNotifier {
  bool _arabic = true;

  bool get isArabic => _arabic;

  TextDirection get direction =>
      _arabic ? TextDirection.rtl : TextDirection.ltr;

  void toggleLanguage() {
    _arabic = !_arabic;
    notifyListeners();
  }

  String tr(String key) {
    final table = _arabic ? _ar : _en;
    return table[key] ??
        (_arabic ? prayerStringsAr : prayerStringsEn)[key] ??
        key;
  }
}

final AppState appState = AppState();

const Map<String, String> _ar = {
  'appName': 'نور الهداية',
  'appNameSub': 'Noor Al-Hidayah',
  'tagline': 'رفيقك اليومي في الصلاة والقرآن والأذكار',
  'description':
      'تطبيق إسلامي شامل يجمع مواقيت الصلاة والقرآن الكريم والأذكار والأدعية في تجربة واحدة هادئة وموثوقة.',
  'getStarted': 'ابدأ الآن',
  'haveAccount': 'لدي حساب بالفعل',
  'switchLanguage': 'English',
  'credit': 'By Abdel Rahmen Ben Romdhan',
  'back': 'رجوع',
  'createAccount': 'إنشاء حساب',
  'createAccountSub': 'ابدأ رحلتك مع نور الهداية بحساب مجاني',
  'login': 'تسجيل الدخول',
  'loginSub': 'أهلًا بعودتك، أكمل رحلتك من حيث توقفت',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'confirmPassword': 'تأكيد كلمة المرور',
  'showPassword': 'إظهار كلمة المرور',
  'hidePassword': 'إخفاء كلمة المرور',
  'haveAccountQ': 'لديك حساب بالفعل؟',
  'noAccountQ': 'ليس لديك حساب؟',
  'errEmailEmpty': 'أدخل بريدك الإلكتروني',
  'errEmailInvalid': 'البريد الإلكتروني غير صالح',
  'errPasswordEmpty': 'أدخل كلمة المرور',
  'errPasswordShort': 'كلمة المرور يجب ألا تقل عن 8 أحرف',
  'errPasswordMismatch': 'كلمتا المرور غير متطابقتين',
  'successDemo': 'البيانات صحيحة. ربط الحساب بالخادم قادم في الخطوة التالية.',
// شاشة الحساب والملف الشخصي
'noName': 'بدون اسم',
'points': 'نقاط',
'level': 'مستوى',
'streak': 'أيام متتالية',
'levelProgress': 'التقدم للمستوى القادم',
'editProfile': 'تعديل الملف الشخصي',
'signOut': 'تسجيل الخروج',
'signOutConfirmTitle': 'تسجيل الخروج؟',
'signOutConfirmBody': 'هل أنت متأكد من تسجيل الخروج من الحساب؟',
'cancel': 'إلغاء',
'public': 'عام',
'private': 'خاص',
'profileVisibility': 'ظهور الملف الشخصي',
'name': 'الاسم',
'bio': 'نبذة تعريفية',
'save': 'حفظ',
'profileSaved': 'تم حفظ التعديلات بنجاح',
'chooseAvatar': 'اختر الصورة الرمزية',
'man': 'رجل',
'woman': 'امرأة',
'tapToChangeAvatar': 'اضغط على الصورة لتغييرها',
'errNameShort': 'الاسم يجب أن يكون حرفين على الأقل',
'errBioLong': 'النبذة طويلة جداً (200 حرف كحد أقصى)',
// التحديات والكوبون
'tabChallenge': 'التحديات',
'challenges': 'التحديات',
'dailyChallengeTitle': 'تحدي اليوم',
'dailyChallengeDesc': '5 أسئلة تتجدد كل يوم. كل إجابة صحيحة = 20 نقطة',
'startChallenge': 'ابدأ التحدي',
'redeemCoupon': 'استبدال كوبون',
'redeemCouponDesc': 'أدخل كود الخصم للحصول على نقاط',
'enterCouponCode': 'أدخل الكود...',
'redeem': 'استبدال',
'couponSuccess': 'تم! حصلت على 1000 نقطة 🎉',
'couponInvalid': 'الكود غير صالح',
'settings': 'الإعدادات',
'couponAlreadyUsed': 'لقد استخدمت هذا الكود مسبقاً',
'verified': 'موثوق',
'getVerified': 'توثيق الحساب',
'getVerifiedDesc': 'أضف صورة شخصية وفحص وجه للحصول على شعار التوثيق',
'verifyNow': 'وثّق حسابي الآن',
'verifiedDone': '🎉 تم توثيق حسابك!',
'store': 'المتجر',
'storeDesc': 'اشترِ خلفيات وأصوات ومؤذنين بالنقاط',
'challengeQuestionOf': 'سؤال',
'challengeCorrect': 'إجابة صحيحة! 🎉',
'challengeWrong': 'إجابة خاطئة ❌',
'challengeResult': 'النتيجة',
'challengeGreatJob': 'أحسنت! 🎉',
'challengeKeepTrying': 'حاول مرة أخرى غداً 💪',
'challengeBack': 'العودة',
'challengeDoneToday': 'أكملت تحدي اليوم!',
'challengeComeBack': 'عد غداً لتحدٍّ جديد',
'challengeDone': 'تم اليوم ✓',
'challengeAlreadyPlayed': 'أكملت تحدي اليوم، عد غداً',
'exitChallenge': 'الخروج من التحدي؟',
'exitChallengeBody': 'سيُلغى تقدمك الحالي في هذا التحدي.',
'exit': 'خروج',
'yourBalance': 'رصيدك',
'tabBackgrounds': 'الخلفيات',
'tabVoices': 'القراء',
'tabAdhans': 'المؤذنون',
'tabThemes': 'الثيمات',
'active': 'مفعّل',
'tapToActivate': 'اضغط للتفعيل',
'price': 'السعر',
'buy': 'شراء',
'confirmPurchase': 'تأكيد الشراء',
'purchaseSuccess': 'تم الشراء بنجاح 🎉',
'itemActivated': 'تم التفعيل ✓',
'notEnoughPoints': 'نقاطك غير كافية',
'myPurchases': 'مشترياتي',
'noPurchases': 'لا توجد مشتريات بعد',
'credits': 'شكر وتقدير',
'iconsCredit': 'بعض الأيقونات من Flaticon.com',
'adhkar': 'الأذكار',
'adhkarSubtitle': 'أذكار الصباح والمساء وبعد الصلاة والنوم',
'items': 'ذكر',
'done': 'مكتمل',
'completed': 'تم ✓',
'reset': 'إعادة',
'tapToCount': 'اضغط للتسبيح • اضغط مطولاً للإعادة',
// التسبيح
'tasbeeh': 'التسبيح',
'tasbeehToday': 'اليوم',
'tasbeehTotal': 'الإجمالي',
'tasbeehOpen': 'مفتوح',
'tasbeehChooseDhikr': 'اختر الذكر',
'tasbeehResetTitle': 'إعادة تعيين العداد؟',
'tasbeehResetBody': 'سيتم إعادة العداد الحالي إلى صفر.',
'tasbeehTapAnywhere': 'اضغط في أي مكان للعد',
'tasbeehCompleted': 'أكملت الهدف ✓',
// الزكاة
'zakat': 'حساب الزكاة',
'zakatDisclaimer': 'هذه حاسبة تقديرية فقط لمساعدتك في حساب الزكاة. ليست مكاناً للصدقة أو إخراج المال. يُرجى مراجعة أهل العلم للتأكد.',
'zakatFetchingPrices': 'جاري جلب الأسعار الحية...',
'zakatPriceFailed': 'فشل جلب الأسعار - اضغط لإعادة المحاولة',
'zakatPriceLive': 'أسعار حية',
'zakatResult': 'النتيجة',
'zakatNisab': 'النصاب',
'zakatDueAmount': 'الزكاة الواجبة',
'zakatDueWeight': 'الزكاة الواجبة (وزن)',
'zakatBelowNisab': 'لم يبلغ النصاب - لا زكاة',
'zakatTabMoney': 'المال',
'zakatTabGold': 'الذهب',
'zakatTabSilver': 'الفضة',
'zakatTabCrops': 'الزروع',
'zakatTabLivestock': 'الأنعام',
'currencyUnit': 'عملة',
'zakatMoneyAmount': 'المبلغ',
'zakatMoneyNisabHint': 'النصاب = 85 جرام ذهب',
'zakatGoldPrice': 'سعر جرام الذهب',
'zakatGoldPrice24': 'سعر جرام الذهب عيار 24',
'zakatGoldWeight': 'الوزن',
'zakatKarat': 'العيار',
'zakatPureWeight': 'ما يعادل الذهب الخالص',
'zakatGoldValue': 'قيمة الذهب',
'zakatSilverWeight': 'وزن الفضة',
'zakatSilverPrice': 'سعر جرام الفضة',
'zakatSilverValue': 'قيمة الفضة',
'zakatCropWeight': 'وزن المحصول',
'zakatIrrigationType': 'طريقة الري',
'zakatRainFed': 'بماء المطر',
'zakatIrrigated': 'بري بمؤونة',
'zakatCropRate': 'نسبة الزكاة',
'zakatAnimalType': 'نوع الأنعام',
'zakatAnimalCount': 'العدد',
'zakatHead': 'رأس',
'zakat_sheep': 'غنم',
'zakat_cow': 'بقر',
'zakat_camel': 'إبل',
'zakatNoZakat': 'لا زكاة',
'zakatSheep': 'شاة',
'zakatCalf': 'بقرة',
'zakatTabii': 'تبيع',
'zakatMusinnah': 'مسنة',
'zakatBintMakhad': 'بنت مخاض',
'zakatBintLabun': 'بنت لبون',
'zakatHiqqah': 'حقة',
'zakatJadhah': 'جذعة',
// الزكاة — إضافات
'zakatChooseCurrency': 'اختر العملة',
'zakatSearchCurrency': 'ابحث عن عملة...',
'zakatLivePrices': 'أسعار حية',
'zakatLiveGold': 'سعر جرام الذهب:',
'zakatLiveSilver': 'سعر جرام الفضة:',
'duas': 'الأدعية',
'duasSubtitle': 'أدعية قرآنية ونبوية لكل الأحوال',
'copy': 'نسخ',
'share': 'مشاركة',
'copied': 'تم النسخ ✓',
'copiedToShare': 'تم النسخ — يمكنك لصقه في أي تطبيق',
'khatmPlan': 'خطة ختم القرآن',
'khatmWelcome': 'ابدأ رحلتك مع القرآن',
'khatmWelcomeDesc': 'اختر المدة المناسبة لك، وسنقسم لك القرآن على أيام.',
'khatmChooseDuration': 'اختر المدة',
'khatmTodayWard': 'ورد اليوم',
'khatmTodayDone': '🎉 أكملت ورد اليوم!',
'khatmTodayRemaining': 'باقي',
'khatmPages': 'صفحة',
'khatmDaysLeft': 'أيام متبقية',
'khatmPercent': 'التقدم',
'khatmCurrentPage': 'آخر صفحة وصلت',
'khatmUpdatePage': 'تحديث الصفحة',
'khatmUpdateTitle': 'حدّث الصفحة',
'khatmUpdateBody': 'أدخل رقم الصفحة التي وصلت إليها',
'khatmInvalidPage': 'رقم الصفحة غير صحيح (1-604)',
'khatmAdded': 'أُضيف',
'khatmResetPlan': 'إعادة تعيين الخطة',
'khatmResetTitle': 'إعادة تعيين؟',
'khatmResetBody': 'سيتم حذف كل التقدم في خطة الختم.',
'khatmCompleteTitle': '🎉 أكملت الختمة!',
'khatmCompleteBody': 'ما شاء الله! أتممت ختم القرآن الكريم. جعله الله في ميزان حسناتك.',
'khatmStartNew': 'ابدأ ختمة جديدة',
'khatmHistory': 'آخر الأيام',
'haram': 'المحرمات',
'haramSubtitle': 'ما حرّمه الله ورسوله ﷺ — تجنّبها واجب',
'makruh': 'المكروهات',
'makruhSubtitle': 'ما يُكره شرعاً — تركه أفضل',
'evidence': 'الدليل',
'qiblaNeedLocation': 'يجب تحديد موقعك أولاً لاستخدام البوصلة.',
'qiblaNoSensor': 'الحساس غير متوفر — استخدم الاتجاه المعروض.',
'qiblaAligned': '🎉 أنت متجه إلى القبلة!',
'qiblaRotate': 'أدر جهازك حتى يشير السهم للأعلى',
'qiblaAngle': 'اتجاه القبلة',
'qiblaDistance': 'المسافة إلى مكة',
// المساجد القريبة
'nearbyMosques': 'المساجد القريبة',
'mosquesRadius': 'نطاق البحث',
'mosquesError': 'تعذّر جلب المساجد. تحقق من اتصالك.',
'mosquesNone': 'لا توجد مساجد في هذا النطاق.',
'mosquesNavigate': 'التوجيه',
'mosquesNoMapsApp': 'لا يوجد تطبيق خرائط على جهازك',
'km': 'كم',
'retry': 'إعادة المحاولة',
};

const Map<String, String> _en = {
  'appName': 'Noor Al-Hidayah',
  'appNameSub': 'نور الهداية',
  'tagline': 'Your daily companion for prayer, Quran and remembrance',
  'description':
      'A complete Islamic app bringing prayer times, the Holy Quran, adhkar and duas together in one calm, trustworthy experience.',
  'getStarted': 'Get Started',
  'haveAccount': 'I already have an account',
  'switchLanguage': 'العربية',
  'credit': 'By Abdel Rahmen Ben Romdhan',
  'back': 'Back',
  'createAccount': 'Create Account',
  'createAccountSub': 'Start your journey with Noor Al-Hidayah with a free account',
  'login': 'Sign In',
  'loginSub': 'Welcome back, continue where you left off',
  'email': 'Email',
  'password': 'Password',
  'confirmPassword': 'Confirm password',
  'showPassword': 'Show password',
  'hidePassword': 'Hide password',
  'haveAccountQ': 'Already have an account?',
  'noAccountQ': 'Don’t have an account?',
  'errEmailEmpty': 'Enter your email',
  'errEmailInvalid': 'This email is not valid',
  'errPasswordEmpty': 'Enter your password',
  'errPasswordShort': 'Password must be at least 8 characters',
  'errPasswordMismatch': 'Passwords do not match',
  'successDemo': 'Details look good. Connecting accounts to the server comes in the next step.',
'noName': 'No name',
'points': 'Points',
'level': 'Level',
'streak': 'Day streak',
'levelProgress': 'Progress to next level',
'editProfile': 'Edit Profile',
'signOut': 'Sign Out',
'signOutConfirmTitle': 'Sign out?',
'signOutConfirmBody': 'Are you sure you want to sign out?',
'cancel': 'Cancel',
'public': 'Public',
'private': 'Private',
'profileVisibility': 'Profile visibility',
'name': 'Name',
'bio': 'Bio',
'save': 'Save',
'profileSaved': 'Changes saved successfully',
'chooseAvatar': 'Choose avatar',
'man': 'Man',
'woman': 'Woman',
'tapToChangeAvatar': 'Tap the image to change it',
'errNameShort': 'Name must be at least 2 characters',
'errBioLong': 'Bio is too long (max 200 characters)',
'tabChallenge': 'Challenges',
'challenges': 'Challenges',
'dailyChallengeTitle': 'Daily Challenge',
'dailyChallengeDesc': '5 questions renew daily. 20 points per correct answer.',
'startChallenge': 'Start Challenge',
'redeemCoupon': 'Redeem Coupon',
'redeemCouponDesc': 'Enter a coupon code to get points',
'enterCouponCode': 'Enter code...',
'redeem': 'Redeem',
'couponSuccess': 'Success! You got 1000 points 🎉',
'couponInvalid': 'Invalid code',
'settings': 'Settings',
'couponAlreadyUsed': 'You already used this coupon',
'verified': 'Verified',
'getVerified': 'Get Verified',
'getVerifiedDesc': 'Add a profile picture and face scan to get the badge',
'verifyNow': 'Verify My Account',
'verifiedDone': '🎉 Your account is verified!',
'store': 'Store',
'storeDesc': 'Buy backgrounds, voices and adhans with points',
'challengeQuestionOf': 'Question',
'challengeCorrect': 'Correct! 🎉',
'challengeWrong': 'Wrong ❌',
'challengeResult': 'Result',
'challengeGreatJob': 'Great job! 🎉',
'challengeKeepTrying': 'Try again tomorrow 💪',
'challengeBack': 'Back',
'challengeDoneToday': "Today's challenge is done!",
'challengeComeBack': 'Come back tomorrow for a new challenge',
'challengeDone': 'Done today ✓',
'challengeAlreadyPlayed': "You've completed today's challenge",
'exitChallenge': 'Exit challenge?',
'exitChallengeBody': 'Your current progress will be lost.',
'exit': 'Exit',
'yourBalance': 'Your Balance',
'tabBackgrounds': 'Backgrounds',
'tabVoices': 'Reciters',
'tabAdhans': 'Adhans',
'tabThemes': 'Themes',
'active': 'Active',
'tapToActivate': 'Tap to activate',
'price': 'Price',
'buy': 'Buy',
'confirmPurchase': 'Confirm Purchase',
'purchaseSuccess': 'Purchased successfully 🎉',
'itemActivated': 'Activated ✓',
'notEnoughPoints': 'Not enough points',
'myPurchases': 'My Purchases',
'noPurchases': 'No purchases yet',
'credits': 'Credits',
'iconsCredit': 'Some icons from Flaticon.com',
'adhkar': 'Adhkar',
'adhkarSubtitle': 'Morning, evening, after prayer and sleep adhkar',
'items': 'items',
'done': 'Done',
'completed': 'Done ✓',
'reset': 'Reset',
'tapToCount': 'Tap to count • Long press to reset',
'tasbeeh': 'Tasbeeh',
'tasbeehToday': 'Today',
'tasbeehTotal': 'Total',
'tasbeehOpen': 'Open',
'tasbeehChooseDhikr': 'Choose Dhikr',
'tasbeehResetTitle': 'Reset counter?',
'tasbeehResetBody': 'The current counter will be reset to zero.',
'tasbeehTapAnywhere': 'Tap anywhere to count',
'tasbeehCompleted': 'Target reached ✓',
'zakat': 'Zakat Calculator',
'zakatDisclaimer': 'This is an estimation calculator to help you compute Zakat only. It is not a place for charity or giving money. Please consult scholars to confirm.',
'zakatFetchingPrices': 'Fetching live prices...',
'zakatPriceFailed': 'Failed to load prices - tap to retry',
'zakatPriceLive': 'Live prices',
'zakatResult': 'Result',
'zakatNisab': 'Nisab',
'zakatDueAmount': 'Zakat due',
'zakatDueWeight': 'Zakat due (weight)',
'zakatBelowNisab': 'Below nisab - no zakat',
'zakatTabMoney': 'Money',
'zakatTabGold': 'Gold',
'zakatTabSilver': 'Silver',
'zakatTabCrops': 'Crops',
'zakatTabLivestock': 'Livestock',
'currencyUnit': 'unit',
'zakatMoneyAmount': 'Amount',
'zakatMoneyNisabHint': 'Nisab = 85 grams of gold',
'zakatGoldPrice': 'Gold price per gram',
'zakatGoldPrice24': 'Gold price per gram (24K)',
'zakatGoldWeight': 'Weight',
'zakatKarat': 'Karat',
'zakatPureWeight': 'Pure gold equivalent',
'zakatGoldValue': 'Gold value',
'zakatSilverWeight': 'Silver weight',
'zakatSilverPrice': 'Silver price per gram',
'zakatSilverValue': 'Silver value',
'zakatCropWeight': 'Crop weight',
'zakatIrrigationType': 'Irrigation type',
'zakatRainFed': 'Rain-fed',
'zakatIrrigated': 'Irrigated',
'zakatCropRate': 'Zakat rate',
'zakatAnimalType': 'Animal type',
'zakatAnimalCount': 'Count',
'zakatHead': 'head',
'zakat_sheep': 'Sheep',
'zakat_cow': 'Cows',
'zakat_camel': 'Camels',
'zakatNoZakat': 'No zakat',
'zakatSheep': 'sheep',
'zakatCalf': 'calf',
'zakatTabii': 'Tabii',
'zakatMusinnah': 'Musinnah',
'zakatBintMakhad': 'Bint Makhad',
'zakatBintLabun': 'Bint Labun',
'zakatHiqqah': 'Hiqqah',
'zakatJadhah': 'Jadhah',
'zakatChooseCurrency': 'Choose Currency',
'zakatSearchCurrency': 'Search currency...',
'zakatLivePrices': 'Live prices',
'zakatLiveGold': 'Gold per gram:',
'zakatLiveSilver': 'Silver per gram:',
'duas': 'Duas',
'duasSubtitle': 'Quranic and prophetic duas for all situations',
'copy': 'Copy',
'share': 'Share',
'copied': 'Copied ✓',
'copiedToShare': 'Copied — paste it in any app',
'khatmPlan': 'Khatm Plan',
'khatmWelcome': 'Start your journey with the Quran',
'khatmWelcomeDesc': 'Choose a duration, and we will divide the Quran into daily pages.',
'khatmChooseDuration': 'Choose duration',
'khatmTodayWard': "Today's ward",
'khatmTodayDone': "🎉 Today's ward is done!",
'khatmTodayRemaining': 'Remaining',
'khatmPages': 'pages',
'khatmDaysLeft': 'Days left',
'khatmPercent': 'Progress',
'khatmCurrentPage': 'Last page reached',
'khatmUpdatePage': 'Update page',
'khatmUpdateTitle': 'Update page',
'khatmUpdateBody': 'Enter the page number you reached',
'khatmInvalidPage': 'Invalid page number (1-604)',
'khatmAdded': 'Added',
'khatmResetPlan': 'Reset plan',
'khatmResetTitle': 'Reset?',
'khatmResetBody': 'All progress in the khatm plan will be deleted.',
'khatmCompleteTitle': '🎉 Khatma complete!',
'khatmCompleteBody': 'MashaAllah! You have completed the Quran.',
'khatmStartNew': 'Start a new khatma',
'khatmHistory': 'Recent days',
'haram': 'Prohibitions',
'haramSubtitle': 'What Allah and His Messenger ﷺ forbade — avoiding is obligatory',
'makruh': 'Disliked Matters',
'makruhSubtitle': 'What is disliked in Islam — avoiding is better',
'evidence': 'Evidence',
'qiblaNeedLocation': 'You must set your location first to use the compass.',
'qiblaNoSensor': 'Sensor unavailable — use the displayed direction.',
'qiblaAligned': '🎉 You are facing the Qibla!',
'qiblaRotate': 'Rotate your device until the arrow points up',
'qiblaAngle': 'Qibla direction',
'qiblaDistance': 'Distance to Makkah',
'nearbyMosques': 'Nearby Mosques',
'mosquesRadius': 'Search radius',
'mosquesError': 'Could not fetch mosques. Check your connection.',
'mosquesNone': 'No mosques found in this radius.',
'mosquesNavigate': 'Navigate',
'mosquesNoMapsApp': 'No maps app on your device',
'km': 'km',
'retry': 'Retry',
};
