const Map<String, String> prayerStringsAr = {
  'locTitle': 'تحديد موقعك',
  'locSub': 'نحتاج موقعك لحساب مواقيت الصلاة بدقة في مدينتك',
  'locAllow': 'السماح بتحديد الموقع',
  'locOr': 'أو',
  'locManualLabel': 'المدينة، الدولة (مثال: Riyadh, Saudi Arabia)',
  'locManualButton': 'استخدم هذه المدينة',
  'locPrivacy': 'يُستخدم موقعك لحساب مواقيت الصلاة فقط، ويمكنك تغييره في أي وقت.',
  'locErrDenied': 'لم يتم السماح بالوصول للموقع. يمكنك إدخال مدينتك يدويًا.',
  'locErrDeniedForever':
      'تم رفض إذن الموقع. فعّله من إعدادات المتصفح أو أدخل مدينتك يدويًا.',
  'locErrService': 'خدمة الموقع مغلقة على جهازك. فعّلها أو أدخل مدينتك يدويًا.',
  'locErrUnavailable':
      'تعذّر تحديد موقعك الآن. حاول مرة أخرى أو أدخل مدينتك يدويًا.',
  'locErrManualEmpty': 'اكتب اسم المدينة والدولة',
  'currentLocation': 'موقعك الحالي',
  'fajr': 'الفجر',
  'sunrise': 'الشروق',
  'dhuhr': 'الظهر',
  'asr': 'العصر',
  'maghrib': 'المغرب',
  'isha': 'العشاء',
  'nextPrayer': 'الصلاة القادمة',
  'remaining': 'المتبقي على الصلاة',
  'ptError':
      'تعذّر تحميل مواقيت الصلاة. تحقق من الاتصال بالإنترنت وحاول مرة أخرى.',
  'retry': 'إعادة المحاولة',
  'changeLocation': 'تغيير الموقع',
  'tabHome': 'الرئيسية',
  'tabPrayer': 'المواقيت',
  'tabQuran': 'القرآن',
  'tabAdhkar': 'الأذكار',
  'tabMore': 'المزيد',
  'greeting': 'السلام عليكم',
  'quickAccess': 'الوصول السريع',
  'qibla': 'القبلة',
  'tasbeeh': 'التسبيح',
  'duas': 'الأدعية',
  'comingSoon': 'هذه الميزة قادمة قريبًا إن شاء الله',
  'soonBadge': 'قريبًا',
  'quranSoon': 'سيكون هنا المصحف الكامل مع القرّاء والتلاوات.',
  'adhkarSoon': 'أذكار الصباح والمساء وما بعد الصلاة.',
  'language': 'اللغة',
  'account': 'الحساب',
  'chooseAvatar': 'اختر صورة ملفك الشخصي',
  'avatarMan': 'رجل',
  'avatarWoman': 'امرأة',
  'tabCommunity': 'المجتمع',
  'communitySoon': 'مجتمع نور الهداية قادم قريبًا، نتشارك فيه الفائدة والدعاء.',
  'myChannel': 'قناتي',
  'channelSub': 'قناة يوتيوب',
  'subscribe': 'اشترك في القناة',
  'openChannel': 'فتح القناة على يوتيوب',
  'latestVideos': 'فيديوهات القناة',
  'videosSoon': 'ستظهر فيديوهات القناة هنا قريبًا.',
  'channelNotSet': 'لم يتم ربط رابط القناة بعد.',
  'linkFailed': 'تعذّر فتح الرابط.',
  'hadiths': 'الأحاديث',
  'nearbyMosques': 'المساجد القريبة',
  'khatmPlan': 'خطة ختم القرآن',
  'zakat': 'حساب الزكاة',
  'haram': 'المحرمات',
  'makruh': 'المكروهات',
  'verseOfDay': 'آية اليوم',
  'hadithOfDay': 'حديث اليوم',
  'duaOfDay': 'دعاء اليوم',
  'ayahWord': 'الآية',
  'nawawiSource': 'الأربعون النووية',
  'quranDuaSource': 'دعاء من القرآن الكريم',
  'showMore': 'عرض المزيد',
  'showLess': 'عرض أقل',
  'copy': 'نسخ',
  'copied': 'تم النسخ',
  'dailyMissing': 'المحتوى اليومي غير متوفر بعد.',
  'teacherTitle': 'المعلم',
  'teacherDesc': 'تعلّم تلاوة القرآن الكريم: استمع إلى القارئ، ثم اقرأ بصوتك، ويرشدك المعلم بالذكاء الاصطناعي إلى مواضع المراجعة خطوة بخطوة.',
  'teacherCta': 'ابدأ التعلم',
  'teacherSoon': 'معلم القرآن بالذكاء الاصطناعي قادم قريبًا إن شاء الله',
  'quranTitle': 'القرآن الكريم',
  'searchSurah': 'ابحث عن سورة',
  'noResults': 'لا توجد نتائج',
  'meccan': 'مكية',
  'medinan': 'مدنية',
  'versesWord': 'آية',
  'fontSimple': 'خط عادي',
  'fontUthmani': 'خط عثماني',
  'translationBtn': 'الترجمة',
  'quranLoadError': 'تعذّر تحميل المصحف. تأكد من تشغيل سكربت البيانات.',
  'modeLines': 'أسطر',
  'modePage': 'صفحة كاملة',
  'tafsirBtn': 'التفسير',
  'enlargeBtn': 'تكبير',
  'apologyTitle': 'اعتذار',
  'apologyMsg': 'الخيار "{option}" لا ينطبق في وضع الصفحة الكاملة',
  'apologyOk': 'حسنًا',
  'zoomHint': 'كبّر الصفحة بإصبعين، وحرّكها بإصبع واحد، واضغط مرتين للرجوع.',
  'tafsirSoon': 'التفسير قادم في الخطوة التالية إن شاء الله',
  'apologyTry': 'جرّب وضع الأسطر، وإن شاء الله سيعمل معك بلا مشاكل',
  'tafsirTitle': 'التفسير',
  'tafsirShared': 'ورد تفسير هذه الآية مع الآيات المجاورة.',
  'tafsirError': 'تعذّر تحميل التفسير. تأكد من تشغيل سكربت البيانات.',
  'saveImage': 'حفظ كصورة',
  'preparingImage': 'جاري تجهيز الصورة...',
  'imageError': 'تعذّر تجهيز الصورة، حاول مرة أخرى.',
  'imageUnsupported': 'المشاركة غير مدعومة في هذا المتصفح. جرّبها من هاتفك.',
  'savePosition': 'حفظ المكان',
  'spotSaved': 'تم حفظ مكان القراءة',
  'continueReading': 'متابعة القراءة',
  'savedSpot': 'علامتي المحفوظة',
  'pageLabel': 'صفحة',
  'chooseReciter': 'اختر القارئ',
  'playAyah': 'تشغيل هذه الآية',
  'fullSurah': 'سورة كاملة',
  'ayahByAyah': 'آية بآية',
  'downloadReciter': 'تحميل للاستماع دون إنترنت',
  'downloading': 'جاري التحميل...',
  'downloadDone': 'تم التحميل بنجاح',
  'downloadFailed': 'لم يكتمل التحميل. جرّب مرة أخرى.',
  'alreadyDownloaded': 'هذه السورة محمّلة بالفعل لهذا القارئ',
};

const Map<String, String> prayerStringsEn = {
  'locTitle': 'Set Your Location',
  'locSub': 'We need your location to calculate accurate prayer times for your city',
  'locAllow': 'Allow location access',
  'locOr': 'or',
  'locManualLabel': 'City, Country (e.g. Riyadh, Saudi Arabia)',
  'locManualButton': 'Use this city',
  'locPrivacy':
      'Your location is only used to calculate prayer times, and you can change it any time.',
  'locErrDenied': 'Location access was not allowed. You can enter your city manually.',
  'locErrDeniedForever':
      'Location permission was blocked. Enable it in your browser settings or enter your city manually.',
  'locErrService':
      'Location service is turned off on your device. Turn it on or enter your city manually.',
  'locErrUnavailable':
      'Could not get your location right now. Try again or enter your city manually.',
  'locErrManualEmpty': 'Enter the city and country',
  'currentLocation': 'Your current location',
  'fajr': 'Fajr',
  'sunrise': 'Sunrise',
  'dhuhr': 'Dhuhr',
  'asr': 'Asr',
  'maghrib': 'Maghrib',
  'isha': 'Isha',
  'nextPrayer': 'Next prayer',
  'remaining': 'Time remaining',
  'ptError':
      'Could not load prayer times. Check your internet connection and try again.',
  'retry': 'Try again',
  'changeLocation': 'Change location',
  'tabHome': 'Home',
  'tabPrayer': 'Prayer',
  'tabQuran': 'Quran',
  'tabAdhkar': 'Adhkar',
  'tabMore': 'More',
  'greeting': 'Assalamu Alaikum',
  'quickAccess': 'Quick access',
  'qibla': 'Qibla',
  'tasbeeh': 'Tasbeeh',
  'duas': 'Duas',
  'comingSoon': 'This feature is coming soon, God willing',
  'soonBadge': 'Coming soon',
  'quranSoon': 'The full Quran with reciters and recitations will be here.',
  'adhkarSoon': 'Morning, evening and after-prayer adhkar.',
  'language': 'Language',
  'account': 'Account',
  'chooseAvatar': 'Choose your profile picture',
  'avatarMan': 'Man',
  'avatarWoman': 'Woman',
  'tabCommunity': 'Community',
  'communitySoon': 'The Noor Al-Hidayah community is coming soon, to share benefits and duas together.',
  'myChannel': 'My Channel',
  'channelSub': 'YouTube channel',
  'subscribe': 'Subscribe to the channel',
  'openChannel': 'Open the channel on YouTube',
  'latestVideos': 'Channel videos',
  'videosSoon': 'The channel videos will appear here soon.',
  'channelNotSet': 'The channel link has not been set yet.',
  'linkFailed': 'Could not open the link.',
  'hadiths': 'Hadiths',
  'nearbyMosques': 'Nearby Mosques',
  'khatmPlan': 'Quran Khatm Plan',
  'zakat': 'Zakat Calculator',
  'haram': 'Prohibitions',
  'makruh': 'Disliked Acts',
  'verseOfDay': 'Verse of the Day',
  'hadithOfDay': 'Hadith of the Day',
  'duaOfDay': 'Dua of the Day',
  'ayahWord': 'Verse',
  'nawawiSource': 'An-Nawawi Forty Hadith',
  'quranDuaSource': 'Supplication from the Quran',
  'showMore': 'Show more',
  'showLess': 'Show less',
  'copy': 'Copy',
  'copied': 'Copied',
  'dailyMissing': 'Daily content is not available yet.',
  'teacherTitle': 'Quran Teacher',
  'teacherDesc': 'Learn to recite the Holy Quran: listen to a reciter, recite in your own voice, and the AI teacher guides you to what needs review, step by step.',
  'teacherCta': 'Start learning',
  'teacherSoon': 'The AI Quran Teacher is coming soon, God willing',
  'quranTitle': 'The Holy Quran',
  'searchSurah': 'Search for a surah',
  'noResults': 'No results',
  'meccan': 'Meccan',
  'medinan': 'Medinan',
  'versesWord': 'verses',
  'fontSimple': 'Simple font',
  'fontUthmani': 'Uthmani font',
  'translationBtn': 'Translation',
  'quranLoadError': 'Could not load the Quran. Make sure the data script was run.',
  'modeLines': 'Lines',
  'modePage': 'Full page',
  'tafsirBtn': 'Tafsir',
  'enlargeBtn': 'Enlarge',
  'apologyTitle': 'Sorry',
  'apologyMsg': 'The option "{option}" does not apply in full-page mode',
  'apologyOk': 'OK',
  'zoomHint': 'Pinch with two fingers to zoom, drag to move, and double-tap to reset.',
  'tafsirSoon': 'Tafsir is coming in the next step, God willing',
  'apologyTry': 'Try the Lines mode, and it will work for you without any problem, God willing',
  'tafsirTitle': 'Tafsir',
  'tafsirShared': 'This verse is explained together with the neighbouring verses.',
  'tafsirError': 'Could not load the tafsir. Make sure the data script was run.',
  'saveImage': 'Save as image',
  'preparingImage': 'Preparing the image...',
  'imageError': 'Could not prepare the image, please try again.',
  'imageUnsupported': 'Sharing is not supported in this browser. Try it on your phone.',
  'savePosition': 'Save spot',
  'spotSaved': 'Reading spot saved',
  'continueReading': 'Continue reading',
  'savedSpot': 'My saved spot',
  'pageLabel': 'Page',
  'chooseReciter': 'Choose reciter',
  'playAyah': 'Play this verse',
  'fullSurah': 'Full surah',
  'ayahByAyah': 'Ayah by ayah',
  'downloadReciter': 'Download for offline listening',
  'downloading': 'Downloading...',
  'downloadDone': 'Download complete',
  'downloadFailed': 'Download did not finish. Please try again.',
  'alreadyDownloaded': 'This surah is already downloaded for this reciter',
};
