const Map<String, String> prayerStringsAr = {
  'locTitle': 'تحديد موقعك',
  'locSub': 'نحتاج موقعك لحساب مواقيت الصلاة بدقة في مدينتك',
  'locAllow': 'السماح بتحديد الموقع',
  'locOr': 'أو',
  'locManualLabel': 'المدينة، الدولة (مثال: Riyadh, Saudi Arabia)',
  'locManualButton': 'استخدم هذه المدينة',
  'locPrivacy': 'يُستخدم موقعك لحساب مواقيت الصلاة فقط، ويمكنك تغييره في أي وقت.',
  'locErrDenied': 'لم يتم السماح بالوصول للموقع. يمكنك إدخال مدينتك يدويًا.',
  'locErrDeniedForever':
      'تم رفض إذن الموقع. فعّله من إعدادات المتصفح أو أدخل مدينتك يدويًا.',
  'locErrService': 'خدمة الموقع مغلقة على جهازك. فعّلها أو أدخل مدينتك يدويًا.',
  'locErrUnavailable':
      'تعذّر تحديد موقعك الآن. حاول مرة أخرى أو أدخل مدينتك يدويًا.',
  'locErrManualEmpty': 'اكتب اسم المدينة والدولة',
  'currentLocation': 'موقعك الحالي',
  'fajr': 'الفجر',
  'sunrise': 'الشروق',
  'dhuhr': 'الظهر',
  'asr': 'العصر',
  'maghrib': 'المغرب',
  'isha': 'العشاء',
  'nextPrayer': 'الصلاة القادمة',
  'remaining': 'المتبقي على الصلاة',
  'ptError':
      'تعذّر تحميل مواقيت الصلاة. تحقق من الاتصال بالإنترنت وحاول مرة أخرى.',
  'retry': 'إعادة المحاولة',
  'changeLocation': 'تغيير الموقع',
  'tabHome': 'الرئيسية',
  'tabPrayer': 'المواقيت',
  'tabQuran': 'القرآن',
  'tabAdhkar': 'الأذكار',
  'tabMore': 'المزيد',
  'greeting': 'السلام عليكم',
  'quickAccess': 'الوصول السريع',
  'qibla': 'القبلة',
  'tasbeeh': 'التسبيح',
  'duas': 'الأدعية',
  'comingSoon': 'هذه الميزة قادمة قريبًا إن شاء الله',
  'soonBadge': 'قريبًا',
  'quranSoon': 'سيكون هنا المصحف الكامل مع القرّاء والتلاوات.',
  'adhkarSoon': 'أذكار الصباح والمساء وما بعد الصلاة.',
  'language': 'اللغة',
  'account': 'الحساب',
  'chooseAvatar': 'اختر صورة ملفك الشخصي',
  'avatarMan': 'رجل',
  'avatarWoman': 'امرأة',
  'tabCommunity': 'المجتمع',
  'communitySoon': 'مجتمع نور الهداية قادم قريبًا، نتشارك فيه الفائدة والدعاء.',
  'myChannel': 'قناتي',
  'channelSub': 'قناة يوتيوب',
  'subscribe': 'اشترك في القناة',
  'openChannel': 'فتح القناة على يوتيوب',
  'latestVideos': 'فيديوهات القناة',
  'videosSoon': 'ستظهر فيديوهات القناة هنا قريبًا.',
  'channelNotSet': 'لم يتم ربط رابط القناة بعد.',
  'linkFailed': 'تعذّر فتح الرابط.',
  'hadiths': 'الأحاديث',
  'nearbyMosques': 'المساجد القريبة',
  'khatmPlan': 'خطة ختم القرآن',
  'zakat': 'حساب الزكاة',
  'haram': 'المحرمات',
  'makruh': 'المكروهات',
  'verseOfDay': 'آية اليوم',
  'hadithOfDay': 'حديث اليوم',
  'duaOfDay': 'دعاء اليوم',
  'ayahWord': 'الآية',
  'nawawiSource': 'الأربعون النووية',
  'quranDuaSource': 'دعاء من القرآن الكريم',
  'showMore': 'عرض المزيد',
  'showLess': 'عرض أقل',
  'copy': 'نسخ',
  'copied': 'تم النسخ',
  'dailyMissing': 'المحتوى اليومي غير متوفر بعد.',
};

const Map<String, String> prayerStringsEn = {
  'locTitle': 'Set Your Location',
  'locSub': 'We need your location to calculate accurate prayer times for your city',
  'locAllow': 'Allow location access',
  'locOr': 'or',
  'locManualLabel': 'City, Country (e.g. Riyadh, Saudi Arabia)',
  'locManualButton': 'Use this city',
  'locPrivacy':
      'Your location is only used to calculate prayer times, and you can change it any time.',
  'locErrDenied': 'Location access was not allowed. You can enter your city manually.',
  'locErrDeniedForever':
      'Location permission was blocked. Enable it in your browser settings or enter your city manually.',
  'locErrService':
      'Location service is turned off on your device. Turn it on or enter your city manually.',
  'locErrUnavailable':
      'Could not get your location right now. Try again or enter your city manually.',
  'locErrManualEmpty': 'Enter the city and country',
  'currentLocation': 'Your current location',
  'fajr': 'Fajr',
  'sunrise': 'Sunrise',
  'dhuhr': 'Dhuhr',
  'asr': 'Asr',
  'maghrib': 'Maghrib',
  'isha': 'Isha',
  'nextPrayer': 'Next prayer',
  'remaining': 'Time remaining',
  'ptError':
      'Could not load prayer times. Check your internet connection and try again.',
  'retry': 'Try again',
  'changeLocation': 'Change location',
  'tabHome': 'Home',
  'tabPrayer': 'Prayer',
  'tabQuran': 'Quran',
  'tabAdhkar': 'Adhkar',
  'tabMore': 'More',
  'greeting': 'Assalamu Alaikum',
  'quickAccess': 'Quick access',
  'qibla': 'Qibla',
  'tasbeeh': 'Tasbeeh',
  'duas': 'Duas',
  'comingSoon': 'This feature is coming soon, God willing',
  'soonBadge': 'Coming soon',
  'quranSoon': 'The full Quran with reciters and recitations will be here.',
  'adhkarSoon': 'Morning, evening and after-prayer adhkar.',
  'language': 'Language',
  'account': 'Account',
  'chooseAvatar': 'Choose your profile picture',
  'avatarMan': 'Man',
  'avatarWoman': 'Woman',
  'tabCommunity': 'Community',
  'communitySoon': 'The Noor Al-Hidayah community is coming soon, to share benefits and duas together.',
  'myChannel': 'My Channel',
  'channelSub': 'YouTube channel',
  'subscribe': 'Subscribe to the channel',
  'openChannel': 'Open the channel on YouTube',
  'latestVideos': 'Channel videos',
  'videosSoon': 'The channel videos will appear here soon.',
  'channelNotSet': 'The channel link has not been set yet.',
  'linkFailed': 'Could not open the link.',
  'hadiths': 'Hadiths',
  'nearbyMosques': 'Nearby Mosques',
  'khatmPlan': 'Quran Khatm Plan',
  'zakat': 'Zakat Calculator',
  'haram': 'Prohibitions',
  'makruh': 'Disliked Acts',
  'verseOfDay': 'Verse of the Day',
  'hadithOfDay': 'Hadith of the Day',
  'duaOfDay': 'Dua of the Day',
  'ayahWord': 'Verse',
  'nawawiSource': 'An-Nawawi Forty Hadith',
  'quranDuaSource': 'Supplication from the Quran',
  'showMore': 'Show more',
  'showLess': 'Show less',
  'copy': 'Copy',
  'copied': 'Copied',
  'dailyMissing': 'Daily content is not available yet.',
};
